// src/redux/constants/dataConstants.js
export const DATA_REQUEST = "DATA_REQUEST";
export const DATA_SUCCESS = "DATA_SUCCESS";
export const DATA_FAIL = "DATA_FAIL";


export const GET_ALL_SERVICES_REQUEST = 'GET_ALL_SERVICES_REQUEST';
export const GET_ALL_SERVICES_SUCCESS = 'GET_ALL_SERVICES_SUCCESS';
export const GET_ALL_SERVICES_FAILURE = 'GET_ALL_SERVICES_FAILURE';

export const GET_ALL_SKILLS = 'GET_ALL_SKILLS';
export const SKILLS_LOADING = 'SKILLS_LOADING';
export const SKILLS_ERROR = 'SKILLS_ERROR';


// Employee Constants
export const EMPLOYEES_LOADING = 'EMPLOYEES_LOADING';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const EMPLOYEES_ERROR = 'EMPLOYEES_ERROR';

// Testimonial Constants
export const TESTIMONIALS_LOADING = 'TESTIMONIALS_LOADING';
export const GET_APPROVED_TESTIMONIALS = 'GET_APPROVED_TESTIMONIALS';
export const TESTIMONIALS_ERROR = 'TESTIMONIALS_ERROR';

// send messgae 
export const MESSAGE_SUBMIT_REQUEST = "MESSAGE_SUBMIT_REQUEST";
export const MESSAGE_SUBMIT_SUCCESS = "MESSAGE_SUBMIT_SUCCESS";
export const MESSAGE_SUBMIT_FAIL = "MESSAGE_SUBMIT_FAIL";

